Const_Email_Templates = [
    "Thank you for your Data Request! You will receive an update on your request status within 5 business days. There is no further action required at this time.",
    "Thank you for contacting us. Our records show that you are not a California citizen. Under the California laws, we are only required to handle these requests by those that a California resident only. If you feel there is a mistake in your residency, please contact us here [Company Email Contact]",
    "Thanks for contacting us. Unfortunately, we cannot fulfill your request at this time. In accordance with our data retention policy, we are retaining or disposing data appropriately for our business-related or commercial purpose. To learn more about our business process, go {Company Privacy Statement]. You may choose to appeal this decision by [Company Email Contact].",
    "Thanks for contacting us. We have checked our records and do not see any of your information in our database. Please check the spelling of your information and try again. If you are having difficulty with your request, feel free to call us here [Company Email Contact].",
    "Thank you for contacting us. We have received your request and will process your  request to [Request Type - (dispose of your data and /or return your data and/or modify your data )]. We will honor your request for at least 12 months. There is no further action needed at this time.",
    "Thank you for contacting us. We have received your (dispose of your data and /or return your data and/or modify your data) request. In order to best serve you, at this time, we are requesting an additional 45-day extension of time to fulfill your request. Thanks for your patience",
    "Thank you for contacting us. We have received your (dispose of your data and /or return your data and/or modify your data) request. In order to best serve you, at this time, we are requesting an additional 30-day extension of time to fulfill your request. Thanks for your patience",
    "Thank you for contacting us. We have completed processing your request for (dispose of your data or modify your data) request. We will honor your request for at least 12 months. There is no further action needed at this time. Feel free to call us here [Company Email Contact].",
    "Thank you for contacting us. We have completed processing return of your data request. We will honor your request for at least 12 months. Please see attached file. There is no further action needed at this time. Feel free to call us here [Company Email Contact]."
]