# Generated by Django 3.1.1 on 2021-03-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-created_at'], 'verbose_name': 'Files'},
        ),
    ]
