# Generated by Django 3.1.1 on 2021-03-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210309_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='extension',
            new_name='file_type',
        ),
    ]
