from django.urls import path
from .views import (ConsumerRequestAPI, ConsumerRequestProgressAPI,
                    ConsumerRequestSetStatus, ConsumerRequestObject,
                    ConsumerReport, ConsumerRequestSend,
                    ConsumerRequestSendCode, ConsumerRequestValidateCode,
                    ConsumerRequestQuestionView, DataReturnView)

urlpatterns = [
    path('request', ConsumerRequestAPI.as_view(), name="consumer_request"),
    path('request/<int:enterprise_id>',
         ConsumerRequestAPI.as_view(),
         name="consumer_request_get"),
    path('send-code',
         ConsumerRequestSendCode.as_view(),
         name="consumer_request_code_send"),
    path('validate-code',
         ConsumerRequestValidateCode.as_view(),
         name="consumer_request_code_validate"),
    path('questions',
         ConsumerRequestQuestionView.as_view(),
         name="consumer_request_question"),
    path('request/send',
         ConsumerRequestSend.as_view(),
         name="consumer_request_complete"),
    path('data-return/<link_id>', DataReturnView.as_view(),
         name="data_return"),
    path('set-status',
         ConsumerRequestSetStatus.as_view(),
         name="consumer_request_set_status"),
    path('report/<int:enterprise_id>',
         ConsumerReport.as_view(),
         name="consumer_report"),
    path('get-progress/<str:period>/',
         ConsumerRequestProgressAPI.as_view(),
         name="consumer_request_progress"),
    path('get-request/<int:request_id>',
         ConsumerRequestObject.as_view(),
         name="get_consumer_request_object"),
]