# Generated by Django 2.2.15 on 2020-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
