# Generated by Django 2.2.15 on 2020-11-05 07:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201103_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
