# Generated by Django 2.2.15 on 2020-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201020_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ce_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
