# Generated by Django 2.2.15 on 2020-10-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_ce_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ce_id',
            new_name='elroi_id',
        ),
    ]
