# Generated by Django 2.2.15 on 2020-11-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201105_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['-created_at']},
        ),
    ]
