# Generated by Django 3.1.1 on 2020-11-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201113_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='payment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
