# Generated by Django 2.2.15 on 2020-10-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201021_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='elroi_id',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
    ]
