# Generated by Django 3.1.1 on 2020-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201113_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
