# Generated by Django 2.2.15 on 2020-10-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='elroi_id',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
