# Generated by Django 2.2.15 on 2020-10-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201026_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='state_resident',
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='elroi_id',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
