# Generated by Django 2.2.15 on 2020-10-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201026_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to=settings.AUTH_USER_MODEL),
        ),
    ]
