# Generated by Django 2.2.15 on 2020-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201026_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
