# Generated by Django 2.2.15 on 2020-10-27 10:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201027_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='allow_api_call',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='allow_email_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='payment',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
