# Generated by Django 2.2.15 on 2020-10-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201027_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.FileField(default='test.png', upload_to=''),
            preserve_default=False,
        ),
    ]
