# Generated by Django 2.2.15 on 2020-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='turn_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
