# Generated by Django 2.2.15 on 2020-10-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201029_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='accounts.Customer')),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_upload', to='accounts.Enterprise')),
            ],
        ),
    ]
