# Generated by Django 2.2.15 on 2020-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='allow_elroi_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='allow_enterprise',
            field=models.BooleanField(default=False),
        ),
    ]
