# Generated by Django 2.2.15 on 2020-11-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201103_1742'),
        ('assessment', '0004_assessment_share_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.AssessmentQuestionAnswers')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
                ('enterprise_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Enterprise')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.AssessmentQuestions')),
                ('user_id', models.ForeignKey(blank=True, max_length=9, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
