# Generated by Django 2.2.15 on 2020-10-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='elroi_id',
            field=models.CharField(default='None', max_length=9),
            preserve_default=False,
        ),
    ]
