# Generated by Django 2.2.15 on 2020-11-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_activitylog_elroi_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Api logs'},
        ),
    ]
