# Generated by Django 2.2.15 on 2020-10-15 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elroi_id', models.CharField(blank=True, max_length=14, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.IntegerField(choices=[(0, 'Return'), (1, 'Modify'), (2, 'Delete')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_data_subject_name', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'For Review'), (1, 'Approved'), (2, 'Processing'), (3, 'Complete'), (4, 'Rejected')], default=0)),
                ('process_end_date', models.DateTimeField(blank=True, null=True)),
                ('request_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('extend_requested', models.BooleanField(default=False)),
                ('extend_requested_date', models.DateTimeField(blank=True, null=True)),
                ('extend_requested_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consumer_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
