# Generated by Django 2.2.15 on 2020-11-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequest',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to='accounts.Enterprise'),
        ),
    ]
