# Generated by Django 2.2.15 on 2020-10-19 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer_request', '0002_consumerrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrequest',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
