# Generated by Django 2.2.15 on 2020-10-23 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0003_consumerrequest_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequest',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
