# Generated by Django 2.2.15 on 2020-10-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0004_auto_20201023_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='consumerrequest',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to='accounts.Enterprise'),
        ),
    ]
