# Generated by Django 2.2.15 on 2020-10-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0005_auto_20201027_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.Customer'),
        ),
    ]
