# Generated by Django 3.1.1 on 2020-12-15 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201117_1241'),
        ('enterprise', '0003_auto_20201113_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseInviteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_key', models.UUIDField(default=uuid.UUID('c514b2d2-a061-4497-afaa-26302062aa72'), unique=True)),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enterprise')),
            ],
            options={
                'db_table': 'enterprise_invite',
                'ordering': ['-created_at'],
            },
        ),
    ]
