# Generated by Django 3.1.1 on 2020-12-15 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_auto_20201215_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinvitemodel',
            name='invite_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
