# Generated by Django 3.1.1 on 2020-12-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_is_2fa_active'),
        ('enterprise', '0006_auto_20201215_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseEmailType',
            fields=[
                ('email_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'enterprise_email_type',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseEmailTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('attachment', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_type_content', to='enterprise.enterpriseemailtype')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_email_template', to='accounts.enterprise')),
            ],
            options={
                'db_table': 'enterprise_email_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
