# Generated by Django 3.1.1 on 2020-12-16 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_is_2fa_active'),
        ('enterprise', '0006_auto_20201215_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseEmailTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_request', models.TextField(blank=True, default='Your request was approved', null=True)),
                ('update_extension', models.TextField(blank=True, default='Your request was extended', null=True)),
                ('reject_request', models.TextField(blank=True, default='Your request was rejected', null=True)),
                ('accept_request', models.TextField(blank=True, default='Your request was completed', null=True)),
                ('disposal_completed', models.TextField(blank=True, default='', null=True)),
                ('data_modified', models.TextField(blank=True, default='', null=True)),
                ('data_returned', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_template', to='accounts.enterprise')),
            ],
            options={
                'db_table': 'enterprise_email_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
