# Generated by Django 3.1.1 on 2020-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_enterpriseemailtemplatemodel_enterpriseemailtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinvitemodel',
            name='email',
            field=models.CharField(max_length=60, verbose_name='Email'),
        ),
    ]
