# Generated by Django 3.1.1 on 2021-01-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_auto_20201222_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseemailtype',
            name='type_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
