# Generated by Django 3.1.1 on 2021-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_enterpriseemailtype_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseemailtemplatemodel',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterpriseemailtemplatemodel',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
