# Generated by Django 3.1.1 on 2021-02-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201222_0734'),
        ('enterprise', '0010_auto_20210124_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseQuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('question_type', models.IntegerField(choices=[(0, 'Text'), (1, 'Yes/No'), (2, 'File')], default=0)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='accounts.enterprise')),
            ],
        ),
    ]
