# Generated by Django 3.1.1 on 2021-02-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_enterprisequestionmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enterprisequestionmodel',
            table='enterprise_questions',
        ),
    ]
