# Generated by Django 3.1.1 on 2021-02-05 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_auto_20210205_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprisequestionmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='enterprisequestionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprisequestionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
