# Generated by Django 3.1.1 on 2021-02-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_auto_20210205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='company_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='website_launched_to',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
