# Generated by Django 3.1.1 on 2021-02-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0014_auto_20210217_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='resident_state',
            field=models.BooleanField(default=False),
        ),
    ]
