# Generated by Django 3.1.1 on 2021-02-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0015_auto_20210223_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseconfigurationmodel',
            name='company_name',
        ),
    ]
