# Generated by Django 3.1.1 on 2021-03-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0016_remove_enterpriseconfigurationmodel_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='file_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='privacy_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
