# Generated by Django 3.1.1 on 2021-03-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210310_1427'),
        ('enterprise', '0017_auto_20210308_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguideuploads',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userguideuploads',
            name='size',
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_conf_background', to='upload.files'),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_conf_logo', to='upload.files'),
        ),
        migrations.AlterField(
            model_name='enterpriseemailtemplatemodel',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_temp_attachment', to='upload.files'),
        ),
        migrations.AlterField(
            model_name='userguideuploads',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_guide_file', to='upload.files'),
        ),
    ]
