# Generated by Django 3.1.1 on 2021-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0019_auto_20210311_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='file_description',
            field=models.TextField(blank=True, default='Please upload verification document to help with your verification. Examples of verification documents include: Drivers License, Passport, State ID. If the required document is not uploaded within 5 business days of the date of submission of this request this request will be rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='privacy_description',
            field=models.TextField(blank=True, default='Your Privacy is very important to us. If you would like to make a request to access your information, please complete the form below. All fields marked with an asterisk (*) are required so we can properly verify your identity.', null=True),
        ),
    ]
