# Generated by Django 2.2.15 on 2020-11-05 22:58

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRequest',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('elroi_id',
                 models.CharField(blank=True, max_length=14, null=True)),
                ('title',
                 models.CharField(blank=True, max_length=255, null=True)),
                ('request_type',
                 models.IntegerField(choices=[(0, 'Return'), (1, 'Modify'),
                                              (2, 'Delete')],
                                     default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('request_form',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True,
                                                                null=True)),
                ('is_data_subject_name', models.BooleanField(default=False)),
                ('status',
                 models.IntegerField(choices=[
                     (0, 'For Review'), (1, 'Approved'), (2, 'Processing'),
                     (3, 'Complete'), (4, 'Rejected')
                 ],
                                     default=0)),
                ('process_end_date', models.DateTimeField(blank=True,
                                                          null=True)),
                ('request_date',
                 models.DateTimeField(blank=True,
                                      default=datetime.datetime.now,
                                      null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('extend_requested', models.BooleanField(default=False)),
                ('extend_requested_date',
                 models.DateTimeField(blank=True, null=True)),
                ('extend_requested_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='enterprise',
                                   to='accounts.Enterprise')),
            ],
            options={
                'db_table': 'consumer_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
