# Generated by Django 3.1.1 on 2020-11-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0004_auto_20201113_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
