# Generated by Django 3.1.1 on 2021-01-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0008_remove_consumerrequest_state_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrequest',
            name='state_resident',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
