# Generated by Django 3.1.1 on 2021-01-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0009_consumerrequest_state_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrequest',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='timeframe',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='consumerrequest',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
