# Generated by Django 3.1.1 on 2021-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0010_auto_20210122_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerrequest',
            name='comment',
        ),
        migrations.AlterField(
            model_name='consumerrequest',
            name='timeframe',
            field=models.IntegerField(choices=[(0, 'GDPR'), (1, 'CCPA')], default=1),
        ),
    ]
