# Generated by Django 3.1.1 on 2021-02-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_enterprisequestionmodel'),
        ('consumer_request', '0012_auto_20210205_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerReqeustQuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('boolean_answer', models.BooleanField(default=False)),
                ('file_answer', models.FileField(upload_to='')),
                ('consumer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_request', to='consumer_request.consumerrequest')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_question', to='enterprise.enterprisequestionmodel')),
            ],
        ),
    ]
