# Generated by Django 3.1.1 on 2021-02-05 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0013_consumerreqeustquestionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerreqeustquestionmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='consumerreqeustquestionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerreqeustquestionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='consumerreqeustquestionmodel',
            table='consumer_request_questions',
        ),
    ]
