# Generated by Django 3.1.1 on 2021-02-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0014_auto_20210205_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerreqeustquestionmodel',
            name='boolean_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
