# Generated by Django 3.1.1 on 2021-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0015_auto_20210205_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
