# Generated by Django 3.1.1 on 2021-02-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0016_consumerrequest_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrequest',
            name='additional_fields',
            field=models.JSONField(default=None),
        ),
    ]
