# Generated by Django 3.1.1 on 2021-02-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0017_consumerrequest_additional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequest',
            name='additional_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
