# Generated by Django 3.1.1 on 2021-02-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0018_auto_20210205_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerrequest',
            name='additional_fields',
        ),
    ]
