# Generated by Django 3.1.1 on 2021-02-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210226_0214'),
        ('consumer_request', '0018_auto_20210205_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerReqeustCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('code', models.CharField(default='', max_length=6)),
                ('lifetime', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_code_enterprise', to='accounts.enterprise')),
            ],
            options={
                'db_table': 'consumer_request_codes',
            },
        ),
    ]
