# Generated by Django 3.1.1 on 2021-03-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210310_1427'),
        ('consumer_request', '0020_auto_20210309_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerrequest',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_request', to='upload.files'),
        ),
        migrations.CreateModel(
            name='DataReturnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(default='', max_length=255, null=True)),
                ('code', models.CharField(default='', max_length=6)),
                ('lifetime', models.DateTimeField(auto_now=True)),
                ('consumer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_dataReturn', to='consumer_request.consumerrequest')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_dataReturn', to='upload.files')),
            ],
            options={
                'db_table': 'data_return',
            },
        ),
    ]
