# Generated by Django 3.1.1 on 2021-03-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_request', '0021_auto_20210313_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datareturnmodel',
            name='lifetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='datareturnmodel',
            name='link_id',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
