# Generated by Django 2.2.15 on 2020-11-05 22:58

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elroi_id', models.CharField(blank=True, max_length=9, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Enterprise')),
            ],
            options={
                'db_table': 'user_guide',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGuideUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', related_query_name='uploads', to='enterprise.UserGuideModel')),
            ],
            options={
                'db_table': 'user_guide_uploads',
                'ordering': ['-created_at'],
                'default_related_name': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseConfigurationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='')),
                ('site_color', models.CharField(max_length=7)),
                ('site_theme', models.CharField(max_length=12)),
                ('background_image', models.FileField(upload_to='')),
                ('website_launched_to', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('resident_state', models.BooleanField(default=True)),
                ('additional_configuration', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='accounts.Enterprise')),
            ],
            options={
                'db_table': 'enterprise_configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Enterprise')),
            ],
            options={
                'db_table': 'enterprise_customer_configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
