# Generated by Django 2.2.15 on 2020-11-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
