# Generated by Django 3.1.1 on 2020-11-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20201105_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerconfiguration',
            name='config',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='additional_configuration',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='site_color',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='site_theme',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
