# Generated by Django 2.2.15 on 2020-10-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_userguidemodel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterpriseconfigurationmodel',
            old_name='configuration',
            new_name='additional_configuration',
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='background_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='resident_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='site_color',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='site_theme',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='website_launched_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
