# Generated by Django 2.2.15 on 2020-11-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201103_1742'),
        ('enterprise', '0002_auto_20201104_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseconfigurationmodel',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='enterpriseconfigurationmodel',
            name='enterprise_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='accounts.Enterprise'),
            preserve_default=False,
        ),
    ]
