# Generated by Django 2.2.15 on 2020-11-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20201104_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseconfigurationmodel',
            name='title',
        ),
    ]
