# Generated by Django 2.2.15 on 2020-11-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_remove_enterpriseconfigurationmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerconfiguration',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Enterprise'),
        ),
    ]
