# Generated by Django 2.2.15 on 2020-10-30 00:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_auto_20201029_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='additional_configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to=settings.AUTH_USER_MODEL),
        ),
    ]
