# Generated by Django 3.1.1 on 2020-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_auto_20201105_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='site_color',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='enterpriseconfigurationmodel',
            name='site_theme',
            field=models.JSONField(blank=True),
        ),
    ]
