// Login Page

export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const LOGOUT = 'LOGOUT';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const SIGNUP_REQUEST_ERROR = 'SIGNUP_REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SENDING_SIGNUP_REQUEST = 'SENDING_SIGNUP_REQUEST';
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';
export const SENDING_VERIFY_CODE = 'SENDING_VERIFY_CODE';