# Generated by Django 3.1.1 on 2020-12-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201117_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='enterprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.enterprise'),
        ),
    ]
