# Generated by Django 3.1.1 on 2020-12-15 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elroi_id', models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.enterprise')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
