# Generated by Django 3.1.1 on 2020-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201215_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='time_frame',
            field=models.CharField(blank=True, default='both', max_length=255, null=True),
        ),
    ]
