# Generated by Django 3.1.1 on 2020-12-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_enterprise_time_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_2fa_active',
            field=models.BooleanField(default=False),
        ),
    ]
