# Generated by Django 3.1.1 on 2020-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_is_2fa_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=60, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='email',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='notification_email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Email'),
        ),
    ]
