# Generated by Django 3.1.1 on 2021-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201222_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='login_failed',
            field=models.IntegerField(default=0),
        ),
    ]
