# Generated by Django 3.1.1 on 2021-02-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210210_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='allow_api_call',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='allow_email_data',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='current_plan_end',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='elroi_id',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='second_color',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='site_color',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='trial_end',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='trial_start',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='turn_off_date',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='web',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='elroi_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.AddField(
            model_name='account',
            name='elroi_id',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
    ]
