# Generated by Django 3.1.1 on 2021-03-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210310_1427'),
        ('accounts', '0015_auto_20210226_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_logo', to='upload.files'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_logo', to='upload.files'),
        ),
    ]
